/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chenxin' at '9/12/16 11:27 AM' with Gradle 2.13
 *
 * @author chenxin, @date 9/12/16 11:27 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
